// ES6 is a future of JavaScript.
// In 1996 , JS was created.
// In 1997 , It was then submitted to ECMA International for standardization, which resulted in ECMAScript.

// In 2015 , Decided to switch to annual releases of ECMAScript. Also known as ES6

// Topics in ES6 :-
// 1. Let & const
// 2. Template String 
// 3. Arrow Function
// 4. Destructuring
// 5. Object Props
// 6. Default Arguments
// 7. Arrays in ES6
// 8. New No. methods
// 9. New Global Methods

